### ISSUE TITLE
Gulp watch

### ISSUE THREAD

**Issue by rdengate** [TerriaJS/terrarium#5]
I'm not 100% sure this is working. Sometimes it seemed I needed to run gulp merge-datasources-terrarium to get the data as expected. I will see whether I can reproduce this, and fix if I can.

**Comment by kring** [comment]
Yes I believe watch doesn't watch the datasources.  This is an AREMI-specific problem, in NM the watch works (but uses totally different tech, not ejs).

**Comment by rdengate** [comment]
Aha ok. Thanks! That makes sense.
